const Type = {
    logInS: "LOGIN_SUCCESS",
    logInE: "LOGIN_ERROR",
    signUpS: "SIGNUP_SUCCESS",
    signUpE: "SIGNUP_ERROR",
    remove: "REMOVE",
    currentUser: "CURRENT_USER",
    currentUserError: "CURRENT_USER_NULL",
    logOut: "LOGOUT",
    logInVE: "LOGIN_VALIDATION_EMAIL",
    logInVP: "LOGIN_VALIDATION_PASSWORD",
    SignUpVE: "SINGUP_VALIDATION_EMAIL",
    SignUpVP: "SINGUP_VALIDATION_PASSWORD",
    SignUpVS: "SINGUP_VALIDATION_STATUS",
    validate: "VALIDATION",
    removeErrorMess: "REMOVE_ERROR_MESSAGES",
    removeErrorMessC: "REMOVE_ERROR_MESSAGES_Company",
    errorInfoC: "ERROR_INFO_COMPANY",
    newStudent: "NEW_STUDENT",
    pervDataOfStudents: "PERVIOUS_DATA_OF_STUDENTS",
    updateStudent: "UPDATE_CURRENT_STUDENT",
    newCompany: "NEW_COMPANY",
    pervDataOfCompanies: "PERVIOUS_DATA_OF_COMPANIES",
    updateCompany: "UPDATE_CURRENT_COMPANY",
    removeErrorMessPC: "REMOVE_ERROR_MESSAGES_POST_COMPANY",
    errorPostC: "ERROR_POST_COMPANY",
    newVacancy: "NEW_VACANCIES",
    pervDataOfVacancies: "PERVIOUS_DATA_OF_VACANCIES",
    blockc: "BLOCK_STUDENT",
    blocks: "BLOCK_COMPANY",
}
export default Type;